<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE products [
	<!ELEMENT products (product*)>

	<!ELEMENT product (added-on, category, producer, model, description, features, dimensions, price)>

	<!ELEMENT added-on (#PCDATA)>

	<!ELEMENT category (#PCDATA)>

	<!ELEMENT producer (#PCDATA)>

	<!ELEMENT model (#PCDATA)>

	<!ELEMENT description (#PCDATA)>

	<!ELEMENT features (feature)>

	<!ELEMENT feature (feature-name, feature-value)>
	<!ELEMENT feature-name (#PCDATA)>
	<!ELEMENT feature-value (#PCDATA)>
	<!ELEMENT dimensions (length, width, height, weight)>
	<!ELEMENT length (unit, value)>
	<!ELEMENT width (unit, value)>
	<!ELEMENT height (unit, value)>
	<!ELEMENT weight (unit, value)>
	<!ELEMENT unit (#PCDATA)>
	<!ELEMENT value (#PCDATA)>

	<!ELEMENT price (currency, cost)>
	<!ELEMENT currency (#PCDATA)>
	<!ELEMENT cost (#PCDATA)>

	<!ATTLIST product id ID #REQUIRED>
]>
<products>
	<!-- Product 1 -->
	<product id="pr1">
		<added-on>08-01-2014</added-on>

		<category>Laptop</category>

		<producer>HP</producer>

		<model>ProBook 450</model>

		<description>Good Laptop for Games</description>

		<features>
			<feature>
				<feature-name>CPU</feature-name>
				<feature-value>Intel Core i5-3230M</feature-value>
			</feature>

			<feature>
				<feature-name>RAM</feature-name>
				<feature-value>4GB DDR 3</feature-value>
			</feature>
		</features>

		<dimensions>
			<length>
				<unit>mm</unit>
				<value>459</value>
			</length>

			<width>
				<unit>mm</unit>
				<value>182.6</value>
			</width>

			<height>
				<unit>mm</unit>
				<value>20.4</value>
			</height>

			<weight>
				<unit>kg</unit>
				<value>2.4</value>
			</weight>
		</dimensions>

		<price>
			<currency>BGN</currency>
			<cost>1139</cost>
		</price>
	</product>
</products>
